name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Test OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [25]
        elixir: [1.15]

    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v3

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{matrix.elixir}} 
          otp-version: ${{matrix.otp}}

      - uses: actions/cache@v4
        id: deps-cache
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - uses: actions/cache@v4
        id: build-cache
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Create Nats cluster
        uses: onichandame/nats-action@0.0.0
        with:
          port: "4222" # multiple different ports will start a cluster. single port will start a single server

      - name: test connection to cluster
        uses: onichandame/nats-client-action@0.0.0
        with:
          servers: "nats://localhost:4222"
          cluster: "true"

      - name: Install deps
        run: mix deps.get

      - name: Run tests
        run: mix test
